Adding Latitude and Longitude Coordinates

Objective

    Find the geographic location of each headline in latitude and longitude coordinates from the city/country names.

Workflow

    Load in the pandas DataFrame with headline, countries, and cities.
        If a headline contains multiple cities/countries, decide which single one to keep.
    For each city/country, match the name to the latitude and longitude in geonamescache.
        You can use the function gc.get_cities_by_names_ _(“city_name”).
        Some cities will return multiple matches with the previous function in different countries. You’ll have to decide which city to keep based on a heuristic (rule of thumb).
        If you have trouble, work with a single problematic city until you figure it out, then write a function to apply on all headlines.
    Add longitude and latitude coordinates to your DataFrame for each headline.
        It will be helpful to get the countrycode of each headline at this point.
        If you were not able to find many countries, think about dropping the column. You also need to decide what to do with headlines that have no coordinates.
        You should end up with over 600 headlines that have geographic coordinates.

#### Load in the pandas DataFrame with headline, countries, and cities.

In [26]:
import numpy as np
import pandas as pd

headline_cities_and_countries = pd.read_json("data/headline_cities_and_countries.json")
headline_cities_and_countries = headline_cities_and_countries.replace({None: np.nan})

print(headline_cities_and_countries.head())

                                  headline countries         cities
0                 Zika Outbreak Hits Miami       NaN          Miami
1          Could Zika Reach New York City?       NaN  New York City
2        First Case of Zika in Miami Beach       NaN    Miami Beach
3  Mystery Virus Spreads in Recife, Brazil    Brazil         Recife
4  Dallas man comes down with case of Zika       NaN         Dallas

In [2]:
print(headline_cities_and_countries.head(60))

                                             headline  countries  \
0                            Zika Outbreak Hits Miami        NaN
1                     Could Zika Reach New York City?        NaN
2                   First Case of Zika in Miami Beach        NaN
3             Mystery Virus Spreads in Recife, Brazil     Brazil
4             Dallas man comes down with case of Zika        NaN
5                   Trinidad confirms first Zika case        NaN
6              Zika Concerns are Spreading in Houston        NaN
7               Geneve Scientists Battle to Find Cure        NaN
8               The CDC in Atlanta is Growing Worried        NaN
9                  Zika Infested Monkeys in Sao Paulo        NaN
10              Brownsville teen contracts Zika virus        NaN
11  Mosquito control efforts in St. Louis take new...        NaN
12  San Juan reports 1st U.S. Zika-related death a...        NaN
13                   Flu outbreak in Galveston, Texas        NaN
14                 Zika alert - Manila now threatened        NaN
15                     Zika afflicts 7 in Iloilo City        NaN
16               New Los Angeles Hairstyle goes Viral        NaN
17                      Louisiana Zika cases up to 26        NaN
18               Orlando volunteers aid Zika research        NaN
19                Zika infects pregnant woman in Cebu        NaN
20                Chicago's First Zika Case Confirmed        NaN
21              Tampa Bay Area Zika Case Count Climbs        NaN
22     Bad Water Leads to Sickness in Flint, Michigan        NaN
23                     Baltimore plans for Zika virus        NaN
24          London Health Unit Tracks Mad Cow Disease        NaN
25     Zika cases in Vietnam's Ho Chi Minh City surge    Vietnam
26                Philadelphia experts track pandemic        NaN
27                             Flu season hits Boston        NaN
28            Scientists in Paris to look for answers        NaN
29           Key Zika Findings in San Diego Institute        NaN
30                     Thailand-Zika Virus in Bangkok   Thailand
31                    Beijing team cracks Zika secret        NaN
32                         Zika spreading to Salvador        NaN
33                 Kuala Lumpur is Hit By Zika Threat        NaN
34                First Zika case confirmed in Yangon        NaN
35             Tallahassee Doctors Discuss Zika Virus        NaN
36                   Zika Virus Reaches San Francisco        NaN
37          New Vaccine on Trial in Bethesda District        NaN
38                 Townsville Zika tests inconclusive        NaN
39              Mandaluyong City under Siege by Virus        NaN
40               Hepatitis E re-emerges in Santa Rosa        NaN
41                       Zika worries in San Salvador        NaN
42                   Zika virus reported in Cleveland        NaN
43              More Zika patients reported in Austin        NaN
44                Zika outbreak in Piracicaba, Brazil     Brazil
45                Lima tries to address Zika Concerns        NaN
46  More people in Toronto are infected with Hepat...        NaN
47                        18 new Zika Cases in Bogota        NaN
48                     Spanish Flu Sighted in Antigua        NaN
49               Brisbane is infested with Meningitis        NaN
50                          Cholera outbreak in Dakar        NaN
51         Zika Virus Transmission Detected in Havana        NaN
52                  Zika symtomps spotted in Key West        NaN
53              Case of Measles Reported in Vancouver        NaN
54  Seattle scientists get $500,000 grant to pursu...        NaN
55           Nashville takes precautions against Zika        NaN
56                      Saint Croix under Zika threat        NaN
57  Fort Collins Encounters Severe Symptoms of Gon...        NaN
58                   Zika surfaces in Klang, Malaysia   Malaysia
59  Rumors about Meningitis spreading in Guatemala...  Guatemala

              cities
0              Miami
1      New York City
2        Miami Beach
3             Recife
4             Dallas
5           Trinidad
6            Houston
7             Geneve
8            Atlanta
9          Sao Paulo
10       Brownsville
11         St. Louis
12          San Juan
13         Galveston
14            Manila
15            Iloilo
16       Los Angeles
17               NaN
18           Orlando
19               NaN
20           Chicago
21             Tampa
22             Flint
23         Baltimore
24            London
25  Ho Chi Minh City
26      Philadelphia
27            Boston
28             Paris
29         San Diego
30           Bangkok
31           Beijing
32          Salvador
33      Kuala Lumpur
34            Yangon
35       Tallahassee
36     San Francisco
37          Bethesda
38        Townsville
39  Mandaluyong City
40        Santa Rosa
41      San Salvador
42         Cleveland
43            Austin
44        Piracicaba
45              Lima
46           Toronto
47            Bogota
48               NaN
49          Brisbane
50             Dakar
51            Havana
52          Key West
53         Vancouver
54           Seattle
55         Nashville
56       Saint Croix
57      Fort Collins
58             Klang
59    Guatemala City

####     If a headline contains multiple cities/countries, decide which single one to keep.

looking at the definition of the function used in the last exercise to extract the ities and countries from headlines it can be seen that only the first from each will be used, and hence multiple cities are ignored here (though we might come back to this later.

In [ ]:
def find_city_and_country_in_headline(headline):
    
    city_match = re.search(city_regex, headline)
    country_match = re.search(country_regex, headline)
    cities = None if not city_match else city_match.group(0)
    countries = None if not country_match else country_match.group(0)
    return dict(headline=headline, countries=countries, cities=cities)

#### For each city/country, match the name to the latitude and longitude in geonamescache.

In [3]:
from geonamescache import GeonamesCache
gc = GeonamesCache()

Create a function to determine the lat, long of a headline according to the following rules
    1. Use lat longs of the city
    2. If the city is duplicated, chose the city with the highest population
    3. If there is no city identified use the country
    4. set lat, long to be nul values

In [ ]:
best_city = max(gc.get_cities_by_name('San Francisco'), key=lambda x: list(x.values())[0]['population'])
print(best_city)

In [ ]:
import math

In [27]:
import json

with open("data/city_accent_mapping.json", "r") as fin:
    city_accent_mapping = json.loads(fin.read())
    
with open("data/country_accent_mapping.json", "r") as fin:
    country_accent_mapping = json.loads(fin.read())

In [28]:
def find_lat_long_for_headline(headline, country, city):

    if city != '-':
        best_city = max(gc.get_cities_by_name(city_accent_mapping[city]), key=lambda x: list(x.values())[0]['population'])
        city_data = list(best_city.values())[0]
        return_lat = city_data['latitude']
        return_long = city_data['longitude']
        return_countrycode = city_data['countrycode']
    elif country != '-':
        the_county = gc.get_countries_by_names()[country]
        the_capital = the_country['capital']
        best_city = max(gc.get_cities_by_name(city_accent_mapping[the_capital]), key=lambda x: list(x.values())[0]['population'])
        city_data = list(best_city.values())[0]
        return_lat = city_data['latitude']
        return_long = city_data['longitude']
        return_countrycode = city_data['countrycode']
    else:        
        return_lat = 0.0
        return_long = 0.0       
        return_countrycode = ""
        
    return (return_lat, return_long, return_countrycode)

In [29]:
headline_cities_and_countries=headline_cities_and_countries.fillna("-")
print( headline_cities_and_countries.head(20))

                                             headline countries         cities
0                            Zika Outbreak Hits Miami         -          Miami
1                     Could Zika Reach New York City?         -  New York City
2                   First Case of Zika in Miami Beach         -    Miami Beach
3             Mystery Virus Spreads in Recife, Brazil    Brazil         Recife
4             Dallas man comes down with case of Zika         -         Dallas
5                   Trinidad confirms first Zika case         -       Trinidad
6              Zika Concerns are Spreading in Houston         -        Houston
7               Geneve Scientists Battle to Find Cure         -         Geneve
8               The CDC in Atlanta is Growing Worried         -        Atlanta
9                  Zika Infested Monkeys in Sao Paulo         -      Sao Paulo
10              Brownsville teen contracts Zika virus         -    Brownsville
11  Mosquito control efforts in St. Louis take new...         -      St. Louis
12  San Juan reports 1st U.S. Zika-related death a...         -       San Juan
13                   Flu outbreak in Galveston, Texas         -      Galveston
14                 Zika alert - Manila now threatened         -         Manila
15                     Zika afflicts 7 in Iloilo City         -         Iloilo
16               New Los Angeles Hairstyle goes Viral         -    Los Angeles
17                      Louisiana Zika cases up to 26         -              -
18               Orlando volunteers aid Zika research         -        Orlando
19                Zika infects pregnant woman in Cebu         -              -

In [30]:
headline_cities_and_countries['latitude'] = 0.0
headline_cities_and_countries['longitude'] = 0.0
headline_cities_and_countries['countrycode'] = ""

for i, row in headline_cities_and_countries.iterrows():
    lat, long, ccode = find_lat_long_for_headline(row['headline'],row['countries'],row['cities'])
    headline_cities_and_countries.at[i, 'latitude'] = lat
    headline_cities_and_countries.at[i, 'longitude'] = long
    headline_cities_and_countries.at[i, 'countrycode'] = ccode
    
print(headline_cities_and_countries.head(50))

                                             headline countries  \
0                            Zika Outbreak Hits Miami         -
1                     Could Zika Reach New York City?         -
2                   First Case of Zika in Miami Beach         -
3             Mystery Virus Spreads in Recife, Brazil    Brazil
4             Dallas man comes down with case of Zika         -
5                   Trinidad confirms first Zika case         -
6              Zika Concerns are Spreading in Houston         -
7               Geneve Scientists Battle to Find Cure         -
8               The CDC in Atlanta is Growing Worried         -
9                  Zika Infested Monkeys in Sao Paulo         -
10              Brownsville teen contracts Zika virus         -
11  Mosquito control efforts in St. Louis take new...         -
12  San Juan reports 1st U.S. Zika-related death a...         -
13                   Flu outbreak in Galveston, Texas         -
14                 Zika alert - Manila now threatened         -
15                     Zika afflicts 7 in Iloilo City         -
16               New Los Angeles Hairstyle goes Viral         -
17                      Louisiana Zika cases up to 26         -
18               Orlando volunteers aid Zika research         -
19                Zika infects pregnant woman in Cebu         -
20                Chicago's First Zika Case Confirmed         -
21              Tampa Bay Area Zika Case Count Climbs         -
22     Bad Water Leads to Sickness in Flint, Michigan         -
23                     Baltimore plans for Zika virus         -
24          London Health Unit Tracks Mad Cow Disease         -
25     Zika cases in Vietnam's Ho Chi Minh City surge   Vietnam
26                Philadelphia experts track pandemic         -
27                             Flu season hits Boston         -
28            Scientists in Paris to look for answers         -
29           Key Zika Findings in San Diego Institute         -
30                     Thailand-Zika Virus in Bangkok  Thailand
31                    Beijing team cracks Zika secret         -
32                         Zika spreading to Salvador         -
33                 Kuala Lumpur is Hit By Zika Threat         -
34                First Zika case confirmed in Yangon         -
35             Tallahassee Doctors Discuss Zika Virus         -
36                   Zika Virus Reaches San Francisco         -
37          New Vaccine on Trial in Bethesda District         -
38                 Townsville Zika tests inconclusive         -
39              Mandaluyong City under Siege by Virus         -
40               Hepatitis E re-emerges in Santa Rosa         -
41                       Zika worries in San Salvador         -
42                   Zika virus reported in Cleveland         -
43              More Zika patients reported in Austin         -
44                Zika outbreak in Piracicaba, Brazil    Brazil
45                Lima tries to address Zika Concerns         -
46  More people in Toronto are infected with Hepat...         -
47                        18 new Zika Cases in Bogota         -
48                     Spanish Flu Sighted in Antigua         -
49               Brisbane is infested with Meningitis         -

              cities  latitude  longitude countrycode
0              Miami  25.77427  -80.19366          US
1      New York City  40.71427  -74.00597          US
2        Miami Beach  25.79065  -80.13005          US
3             Recife  -8.05389  -34.88111          BR
4             Dallas  32.78306  -96.80667          US
5           Trinidad -14.83333  -64.90000          BO
6            Houston  29.76328  -95.36327          US
7             Geneve  46.20222    6.14569          CH
8            Atlanta  33.74900  -84.38798          US
9          Sao Paulo -23.54750  -46.63611          BR
10       Brownsville  25.90175  -97.49748          US
11         St. Louis  38.62727  -90.19789          US
12          San Juan -31.53750  -68.53639          AR
13         Galveston  29.30135  -94.79770          US
14            Manila  14.60420  120.98220          PH
15            Iloilo  10.69694  122.56444          PH
16       Los Angeles  34.05223 -118.24368          US
17                 -   0.00000    0.00000
18           Orlando  28.53834  -81.37924          US
19                 -   0.00000    0.00000
20           Chicago  41.85003  -87.65005          US
21             Tampa  27.94752  -82.45843          US
22             Flint  43.01253  -83.68746          US
23         Baltimore  39.29038  -76.61219          US
24            London  51.50853   -0.12574          GB
25  Ho Chi Minh City  10.82302  106.62965          VN
26      Philadelphia  39.95233  -75.16379          US
27            Boston  42.35843  -71.05977          US
28             Paris  48.85341    2.34880          FR
29         San Diego  32.71571 -117.16472          US
30           Bangkok  13.75398  100.50144          TH
31           Beijing  39.90750  116.39723          CN
32          Salvador -12.97111  -38.51083          BR
33      Kuala Lumpur   3.14120  101.68653          MY
34            Yangon  16.80528   96.15611          MM
35       Tallahassee  30.43826  -84.28073          US
36     San Francisco  37.77493 -122.41942          US
37          Bethesda  38.98067  -77.10026          US
38        Townsville -19.26639  146.80569          AU
39  Mandaluyong City  14.58320  121.04090          PH
40        Santa Rosa  14.31222  121.11139          PH
41      San Salvador  13.68935  -89.18718          SV
42         Cleveland  41.49950  -81.69541          US
43            Austin  30.26715  -97.74306          US
44        Piracicaba -22.72528  -47.64917          BR
45              Lima -12.04318  -77.02824          PE
46           Toronto  43.70011  -79.41630          CA
47            Bogota   4.60971  -74.08175          CO
48                 -   0.00000    0.00000
49          Brisbane -27.46794  153.02809          AU

In [32]:
headline_cities_and_countries = headline_cities_and_countries[(headline_cities_and_countries.latitude != 0.0) & (headline_cities_and_countries.longitude != 0.0)]

headline_cities_and_countries = headline_cities_and_countries.drop(columns=['countries'])
headline_cities_and_countries = headline_cities_and_countries.rename(columns={"cities": "city"})
print(headline_cities_and_countries.head(50))

                                             headline              city  \
0                            Zika Outbreak Hits Miami             Miami
1                     Could Zika Reach New York City?     New York City
2                   First Case of Zika in Miami Beach       Miami Beach
3             Mystery Virus Spreads in Recife, Brazil            Recife
4             Dallas man comes down with case of Zika            Dallas
5                   Trinidad confirms first Zika case          Trinidad
6              Zika Concerns are Spreading in Houston           Houston
7               Geneve Scientists Battle to Find Cure            Geneve
8               The CDC in Atlanta is Growing Worried           Atlanta
9                  Zika Infested Monkeys in Sao Paulo         Sao Paulo
10              Brownsville teen contracts Zika virus       Brownsville
11  Mosquito control efforts in St. Louis take new...         St. Louis
12  San Juan reports 1st U.S. Zika-related death a...          San Juan
13                   Flu outbreak in Galveston, Texas         Galveston
14                 Zika alert - Manila now threatened            Manila
15                     Zika afflicts 7 in Iloilo City            Iloilo
16               New Los Angeles Hairstyle goes Viral       Los Angeles
18               Orlando volunteers aid Zika research           Orlando
20                Chicago's First Zika Case Confirmed           Chicago
21              Tampa Bay Area Zika Case Count Climbs             Tampa
22     Bad Water Leads to Sickness in Flint, Michigan             Flint
23                     Baltimore plans for Zika virus         Baltimore
24          London Health Unit Tracks Mad Cow Disease            London
25     Zika cases in Vietnam's Ho Chi Minh City surge  Ho Chi Minh City
26                Philadelphia experts track pandemic      Philadelphia
27                             Flu season hits Boston            Boston
28            Scientists in Paris to look for answers             Paris
29           Key Zika Findings in San Diego Institute         San Diego
30                     Thailand-Zika Virus in Bangkok           Bangkok
31                    Beijing team cracks Zika secret           Beijing
32                         Zika spreading to Salvador          Salvador
33                 Kuala Lumpur is Hit By Zika Threat      Kuala Lumpur
34                First Zika case confirmed in Yangon            Yangon
35             Tallahassee Doctors Discuss Zika Virus       Tallahassee
36                   Zika Virus Reaches San Francisco     San Francisco
37          New Vaccine on Trial in Bethesda District          Bethesda
38                 Townsville Zika tests inconclusive        Townsville
39              Mandaluyong City under Siege by Virus  Mandaluyong City
40               Hepatitis E re-emerges in Santa Rosa        Santa Rosa
41                       Zika worries in San Salvador      San Salvador
42                   Zika virus reported in Cleveland         Cleveland
43              More Zika patients reported in Austin            Austin
44                Zika outbreak in Piracicaba, Brazil        Piracicaba
45                Lima tries to address Zika Concerns              Lima
46  More people in Toronto are infected with Hepat...           Toronto
47                        18 new Zika Cases in Bogota            Bogota
49               Brisbane is infested with Meningitis          Brisbane
50                          Cholera outbreak in Dakar             Dakar
51         Zika Virus Transmission Detected in Havana            Havana
52                  Zika symtomps spotted in Key West          Key West

    latitude  longitude countrycode
0   25.77427  -80.19366          US
1   40.71427  -74.00597          US
2   25.79065  -80.13005          US
3   -8.05389  -34.88111          BR
4   32.78306  -96.80667          US
5  -14.83333  -64.90000          BO
6   29.76328  -95.36327          US
7   46.20222    6.14569          CH
8   33.74900  -84.38798          US
9  -23.54750  -46.63611          BR
10  25.90175  -97.49748          US
11  38.62727  -90.19789          US
12 -31.53750  -68.53639          AR
13  29.30135  -94.79770          US
14  14.60420  120.98220          PH
15  10.69694  122.56444          PH
16  34.05223 -118.24368          US
18  28.53834  -81.37924          US
20  41.85003  -87.65005          US
21  27.94752  -82.45843          US
22  43.01253  -83.68746          US
23  39.29038  -76.61219          US
24  51.50853   -0.12574          GB
25  10.82302  106.62965          VN
26  39.95233  -75.16379          US
27  42.35843  -71.05977          US
28  48.85341    2.34880          FR
29  32.71571 -117.16472          US
30  13.75398  100.50144          TH
31  39.90750  116.39723          CN
32 -12.97111  -38.51083          BR
33   3.14120  101.68653          MY
34  16.80528   96.15611          MM
35  30.43826  -84.28073          US
36  37.77493 -122.41942          US
37  38.98067  -77.10026          US
38 -19.26639  146.80569          AU
39  14.58320  121.04090          PH
40  14.31222  121.11139          PH
41  13.68935  -89.18718          SV
42  41.49950  -81.69541          US
43  30.26715  -97.74306          US
44 -22.72528  -47.64917          BR
45 -12.04318  -77.02824          PE
46  43.70011  -79.41630          CA
47   4.60971  -74.08175          CO
49 -27.46794  153.02809          AU
50  14.69370  -17.44406          SN
51  23.13302  -82.38304          CU
52  24.55524  -81.78163          US

In [33]:
save_file = "data/headline_cities_and_countries2.csv"
headline_cities_and_countries.to_csv(save_file)